import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Play,Pause,Square,SkipBack,SkipForward,Repeat,Gauge,Volume2,VolumeX,Settings2,Maximize2,Music2,Plus,Trash2,Save,Upload,Download,Search,ChevronRight,MoreHorizontal,CircleHelp,Metronome,SlidersHorizontal,Keyboard,Undo2,Redo2,FileAudio,Radio,ZoomIn,ZoomOut,PanelLeftClose} from 'lucide-react';
import './styles.css';

type Note={string:number;fret:number;duration:number;beat:number;measure:number};
type Song={id:string;title:string;artist:string;bpm:number;key:string;tuning:string;capo:number;notes:Note[];audioName?:string};
const KEY='tablab-pro-v04';
const STR=[4,3,2,1]; const NAMES=['E','A','D','G'];
const OPEN:Record<number,number>={4:40,3:45,2:50,1:55};
const demo:Song={id:'demo',title:'Estudo de Contrabaixo',artist:'TabLab Studio',bpm:92,key:'G',tuning:'E A D G',capo:0,notes:[3,5,2,4,2,4,2,4,3,5,2,4].map((f,i)=>({string:i%4===0?4:i%4===1?3:i%4===2?2:1,fret:f,duration:i%3===0?2:1,beat:i===0?0:0,measure:Math.floor(i/4)}))};
function load():Song[]{try{return JSON.parse(localStorage.getItem(KEY)||'null')||[demo]}catch{return [demo]}}
function freq(m:number){return 440*Math.pow(2,(m-69)/12)}
function midi(n:Note){return OPEN[n.string]+n.fret}
function Tip({label,help,icon,action,active=false,disabled=false}:{label:string;help:string;icon:React.ReactNode;action?:()=>void;active?:boolean;disabled?:boolean}){return <button className={'ib '+(active?'active':'')} onClick={action} disabled={disabled} aria-label={label} title={help}>{icon}<span className="tt"><b>{label}</b><small>{help}</small></span></button>}
function App(){
 const [songs,setSongs]=useState<Song[]>(load); const [sid,setSid]=useState('demo'); const song=songs.find(s=>s.id===sid)||songs[0];
 const [playing,setPlaying]=useState(false),[cursor,setCursor]=useState(0),[speed,setSpeed]=useState(100),[loop,setLoop]=useState(false),[metro,setMetro]=useState(false),[mute,setMute]=useState(false),[vol,setVol]=useState(75),[zoom,setZoom]=useState(100),[panel,setPanel]=useState<'none'|'audio'|'settings'>('none');
 const [selected,setSelected]=useState<number[]>([]),[query,setQuery]=useState(''),[history,setHistory]=useState<Song[][]>([]),[future,setFuture]=useState<Song[][]>([]),[full,setFull]=useState(false),[audio,setAudio]=useState<File|null>(null),[audioUrl,setAudioUrl]=useState('');
 const ctx=useRef<AudioContext|null>(null),gain=useRef<GainNode|null>(null),timer=useRef<number|null>(null),audioEl=useRef<HTMLAudioElement|null>(null),position=useRef(0),lastNote=useRef(-1),lastMetro=useRef(-1),started=useRef(0),startPos=useRef(0),score=useRef<HTMLDivElement|null>(null);
 const starts=useMemo(()=>{let t=0;return song.notes.map(n=>{const s=t;t+=Math.max(.25,n.duration);return s})},[song]);
 const totalBeats=useMemo(()=>song.notes.reduce((a,n)=>a+Math.max(.25,n.duration),0),[song]);
 const currentBeat=starts[cursor]??totalBeats; const filtered=songs.filter(s=>(s.title+' '+s.artist).toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(songs)),[songs]);
 useEffect(()=>{position.current=currentBeat},[currentBeat]);
 useEffect(()=>{if(audioUrl){const a=audioEl.current;a?.pause(); if(a){a.src=audioUrl;a.load();a.preservesPitch=true;(a as any).mozPreservesPitch=true;(a as any).webkitPreservesPitch=true;a.volume=mute?0:vol/100;a.playbackRate=speed/100}}return()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)}},[audioUrl]);
 useEffect(()=>{const a=audioEl.current;if(a){a.volume=mute?0:vol/100;a.playbackRate=speed/100;a.preservesPitch=true;(a as any).mozPreservesPitch=true;(a as any).webkitPreservesPitch=true}},[speed,vol,mute]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.tagName==='INPUT')return;if(e.code==='Space'){e.preventDefault();toggle()}if(e.key==='ArrowRight')setCursor(c=>Math.min(song.notes.length-1,c+1));if(e.key==='ArrowLeft')setCursor(c=>Math.max(0,c-1));if(e.key.toLowerCase()==='l')setLoop(v=>!v);if(e.key.toLowerCase()==='m')setMetro(v=>!v);if(e.key==='Home')setCursor(0);if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[song,playing]);
 function audioContext(){const AC=window.AudioContext||(window as any).webkitAudioContext;if(!ctx.current)ctx.current=new AC();if(ctx.current.state==='suspended')ctx.current.resume();if(!gain.current){gain.current=ctx.current.createGain();gain.current.connect(ctx.current.destination)}gain.current.gain.value=mute?0:vol/100;return ctx.current}
 function tone(m:number,d=.22,level=.18){const c=audioContext(),o=c.createOscillator(),g=c.createGain();o.type='triangle';o.frequency.value=freq(m);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(level,c.currentTime+.012);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+Math.max(.05,d));o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+Math.max(.06,d)+.02)}
 function click(){const c=audioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=lastMetro.current%4===0?1100:760;g.gain.value=.08;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.045)}
 function syncAudio(beat:number){const a=audioEl.current;if(!a||!a.duration||!isFinite(a.duration))return;a.currentTime=Math.min(a.duration,(beat/Math.max(totalBeats,.01))*a.duration)}
 function start(){if(!song.notes.length)return;audioContext();const p=currentBeat>=totalBeats?0:currentBeat;setCursor(song.notes.findIndex((_,i)=>starts[i]>=p)||0);position.current=p;started.current=performance.now();startPos.current=p;audioEl.current?.play().catch(()=>{});setPlaying(true)}
 function pause(){setPlaying(false);audioEl.current?.pause();if(timer.current)cancelAnimationFrame(timer.current);timer.current=null}
 function stop(){pause();setCursor(0);position.current=0;syncAudio(0)}
 function toggle(){playing?pause():start()}
 useEffect(()=>{if(!playing){if(timer.current)cancelAnimationFrame(timer.current);timer.current=null;return}let raf=0;const frame=(now:number)=>{const beatsPerMs=(song.bpm/60000)*(speed/100);const p=startPos.current+(now-started.current)*beatsPerMs;position.current=p;let idx=starts.findIndex((s,i)=>p>=s&&p<s+Math.max(.25,song.notes[i].duration));if(idx<0&&p<totalBeats)idx=Math.max(0,starts.findIndex(s=>s>p)-1);if(idx>=0&&idx!==lastNote.current){lastNote.current=idx;setCursor(idx);tone(midi(song.notes[idx]),Math.min(.5,Math.max(.12,song.notes[idx].duration*.45)));if(metro){const mb=Math.floor(p);if(mb!==lastMetro.current){lastMetro.current=mb;click()}}if(score.current){const el=score.current.querySelector('.cursor') as HTMLElement|null;el?.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'})}}
 if(p>=totalBeats){if(loop){started.current=now;startPos.current=0;position.current=0;lastNote.current=-1;lastMetro.current=-1;setCursor(0);syncAudio(0)}else{stop();return}}raf=requestAnimationFrame(frame);timer.current=raf};raf=requestAnimationFrame(frame);timer.current=raf;return()=>cancelAnimationFrame(raf)},[playing,song,speed,loop,metro,totalBeats,starts]);
 function seekBeat(b:number){const p=Math.max(0,Math.min(totalBeats,b));let i=starts.findIndex((s,j)=>p<s+Math.max(.25,song.notes[j].duration));if(i<0)i=song.notes.length-1;setCursor(i);position.current=p;syncAudio(p);if(playing){started.current=performance.now();startPos.current=p;lastNote.current=-1}}
 function commit(next:Song[]){setHistory(h=>[...h,songs].slice(-30));setFuture([]);setSongs(next)}
 function update(p:Partial<Song>){commit(songs.map(s=>s.id===song.id?{...s,...p}:s))}
 function addNote(){const last=song.notes[song.notes.length-1];update({notes:[...song.notes,{string:last?.string||4,fret:3,duration:1,beat:0,measure:last?last.measure+(last.beat===3?1:0):0}]})}
 function edit(i:number){const n=song.notes[i];const v=prompt('Casa',String(n.fret));if(v!==null)update({notes:song.notes.map((x,j)=>j===i?{...x,fret:Math.max(0,Number(v)||0)}:x)})}
 function remove(){if(!selected.length)return;update({notes:song.notes.filter((_,i)=>!selected.includes(i))});setSelected([])}
 function undo(){if(!history.length)return;const prev=history[history.length-1]!;setFuture(f=>[songs,...f]);setSongs(prev);setHistory(h=>h.slice(0,-1))}
 function redo(){if(!future.length)return;const n=future[0];setHistory(h=>[...h,songs]);setSongs(n);setFuture(f=>f.slice(1))}
 function backup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(songs,null,2)],{type:'application/json'}));a.download='tablab-backup.json';a.click()}
 function restore(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(Array.isArray(x))commit(x)}catch{alert('Backup inválido')}};r.readAsText(f);e.target.value=''}
 function chooseAudio(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(audioUrl)URL.revokeObjectURL(audioUrl);setAudio(f);setAudioUrl(URL.createObjectURL(f));setPanel('audio')}
 function fullscreen(){if(!document.fullscreenElement){document.documentElement.requestFullscreen();setFull(true)}else{document.exitFullscreen();setFull(false)}}
 const noteAt=(i:number)=>song.notes[i];
 return <div className={'app '+(full?'fullscreen':'')}>
 <header><div className="brand"><Music2/><b>TabLab <i>Studio</i></b></div><div className="crumb">Biblioteca <ChevronRight size={14}/> {song.title}</div><div className="topBtns"><Tip label="Desfazer" help="Desfaz a última alteração." icon={<Undo2/>} action={undo} disabled={!history.length}/><Tip label="Refazer" help="Refaz a alteração desfeita." icon={<Redo2/>} action={redo} disabled={!future.length}/><Tip label="Salvar" help="Salva a biblioteca neste navegador." icon={<Save/>} action={()=>localStorage.setItem(KEY,JSON.stringify(songs))}/><Tip label="Backup" help="Baixa um backup completo da biblioteca." icon={<Download/>} action={backup}/><label className="ib" title="Restaurar backup"><Upload/><input hidden type="file" accept="application/json" onChange={restore}/><span className="tt"><b>Restaurar backup</b><small>Importa uma biblioteca salva.</small></span></label></div></header>
 <main><aside><div className="libTitle"><div><b>Minhas músicas</b><small>{songs.length} faixas</small></div><Tip label="Nova música" help="Cria uma nova música para editar." icon={<Plus/>} action={()=>{const s:Song={id:crypto.randomUUID(),title:'Nova música',artist:'',bpm:90,key:'C',tuning:'E A D G',capo:0,notes:[]};commit([...songs,s]);setSid(s.id)}}/></div><div className="search"><Search/><input placeholder="Pesquisar..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{filtered.map(s=><button className={'song '+(s.id===song.id?'chosen':'')} key={s.id} onClick={()=>{setSid(s.id);setCursor(0);pause()}}><span className="cover"><Music2/></span><span><b>{s.title}</b><small>{s.artist||'Sem artista'} · {s.bpm} BPM</small></span><ChevronRight/></button>)}</aside>
 <section className="work"><div className="head"><div><input className="title" value={song.title} onChange={e=>update({title:e.target.value})}/><input className="artist" value={song.artist} placeholder="Artista / compositor" onChange={e=>update({artist:e.target.value})}/></div><div className="tools"><Tip label="Áudio local" help="Carrega MP3, WAV ou M4A para estudo privado." icon={<FileAudio/>} action={()=>document.getElementById('audioPick')?.click()}/><input id="audioPick" hidden type="file" accept="audio/*" onChange={chooseAudio}/><Tip label="Configurações" help="Edita BPM, tom, afinação e capotraste." icon={<Settings2/>} action={()=>setPanel(panel==='settings'?'none':'settings')}/><Tip label={full?'Sair da tela cheia':'Tela cheia'} help="Expande o editor para aproveitar toda a tela." icon={<Maximize2/>} action={fullscreen}/><Tip label="Excluir música" help="Exclui a música atual da biblioteca." icon={<Trash2/>} action={()=>{if(songs.length>1){commit(songs.filter(s=>s.id!==song.id));setSid(songs.find(s=>s.id!==song.id)!.id)}}}/></div></div>
 {panel==='settings'&&<div className="drawer"><label>BPM<input type="number" min="30" max="240" value={song.bpm} onChange={e=>update({bpm:Number(e.target.value)||90})}/></label><label>Tom<input value={song.key} onChange={e=>update({key:e.target.value})}/></label><label>Afinação<input value={song.tuning} onChange={e=>update({tuning:e.target.value})}/></label><label>Capotraste<input type="number" min="0" max="12" value={song.capo} onChange={e=>update({capo:Number(e.target.value)||0})}/></label><span><CircleHelp size={15}/> Passe o cursor nos botões para ver as instruções.</span></div>}
 {panel==='audio'&&<div className="drawer audio"><b>Áudio carregado:</b> {audio?.name}<audio ref={audioEl} controls/></div>}
 <div className="player"><div className="transport"><Tip label="Nota anterior" help="Volta uma nota." icon={<SkipBack/>} action={()=>seekBeat(Math.max(0,currentBeat-.25))}/><Tip label={playing?'Pausar':'Reproduzir'} help={playing?'Pausa no cursor atual.':'Inicia a reprodução da TAB.'} icon={playing?<Pause/>:<Play/>} action={toggle} active={playing}/><Tip label="Parar" help="Para e volta ao início." icon={<Square/>} action={stop}/><Tip label="Próxima nota" help="Avança uma nota." icon={<SkipForward/>} action={()=>seekBeat(Math.min(totalBeats,currentBeat+Math.max(.25,song.notes[cursor]?.duration||1)))}/><Tip label="Loop" help="Repete a música ao chegar ao final." icon={<Repeat/>} action={()=>setLoop(v=>!v)} active={loop}/></div><div className="progress"><b>{cursor+1}/{song.notes.length||0}</b><input type="range" min="0" max={Math.max(.01,totalBeats)} step=".01" value={Math.min(totalBeats,currentBeat)} onChange={e=>seekBeat(Number(e.target.value))}/></div><div className="mixer"><Tip label={mute?'Ativar som':'Silenciar'} help={mute?'Liga o som novamente.':'Silencia o áudio.'} icon={mute?<VolumeX/>:<Volume2/>} action={()=>setMute(v=>!v)}/><input type="range" min="0" max="100" value={vol} onChange={e=>setVol(Number(e.target.value))}/><Tip label="Velocidade" help="50%, 75% ou 100%. A afinação permanece preservada." icon={<Gauge/>} action={()=>setSpeed(speed===100?75:speed===75?50:100)}/><b>{speed}%</b></div></div>
 <div className="toolbar"><div><Tip label="Adicionar nota" help="Acrescenta uma nota ao final da TAB." icon={<Plus/>} action={addNote}/><Tip label="Remover selecionadas" help="Exclui as notas selecionadas." icon={<Trash2/>} action={remove} disabled={!selected.length}/></div><div><Tip label="Metrônomo" help="Ativa o clique sincronizado com o BPM." icon={<Metronome/>} action={()=>setMetro(v=>!v)} active={metro}/><Tip label="Zoom" help="Aumenta a escala da tablatura." icon={<ZoomIn/>} action={()=>setZoom(z=>Math.min(140,z+10))}/><Tip label="Reduzir zoom" help="Reduz a escala da tablatura." icon={<ZoomOut/>} action={()=>setZoom(z=>Math.max(80,z-10))}/><Tip label="Atalhos" help="Mostra os atalhos de teclado do editor." icon={<Keyboard/>} action={()=>alert('Espaço: reproduzir/pausar\n←/→: mover cursor\nHome: início\nL: loop\nM: metrônomo\nCtrl+Z: desfazer')}/></div></div>
 <div className="score" ref={score} style={{'--zoom':zoom/100} as React.CSSProperties}><div className="scoreHead"><b>BAIXO</b><span>4 CORDAS · {song.tuning} · TOM {song.key}</span></div>{song.notes.length?<div className="measures">{Array.from({length:Math.ceil(song.notes.length/4)},(_,m)=><div className="measure" key={m}><div className="mno">{m+1}</div>{STR.map(st=><div className="srow" key={st}><strong>{NAMES[4-st]}</strong><div className="lines">{song.notes.slice(m*4,m*4+4).map((n,j)=>{const i=m*4+j;const active=i===cursor;return <button key={i} className={(active?'cursor ':'')+(selected.includes(i)?'selected':'')} onClick={()=>setSelected(selected.includes(i)?selected.filter(x=>x!==i):[...selected,i])} onDoubleClick={()=>edit(i)}>{n.string===st?n.fret:'—'}</button>})}</div></div>)}</div>)}</div>:<div className="empty"><Music2/><b>Nenhuma nota ainda</b><span>Crie sua tablatura ou carregue um arquivo de estudo.</span><button onClick={addNote}><Plus/> Adicionar primeira nota</button></div>}</div>
 <footer><span><i className="dot"/> Pronto</span><span>Medida {(song.notes[cursor]?.measure??0)+1} · {song.bpm} BPM · {song.tuning}</span><span>Dados locais</span></footer></section></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
